Repository Legacy-Fabric/fabric, pull requests merged in 2020-08, with the labels that each got.

#15 Rendering v1 (not rendering api)
  build.gradle
  fabric-rendering-v1/build.gradle
  fabric-rendering-v1/src/main/java/net/fabricmc/fabric/api/client/render/v1/BlockEntityRendererRegistry.java
  fabric-rendering-v1/src/main/java/net/fabricmc/fabric/api/client/render/v1/EntityRendererRegistry.java
  fabric-rendering-v1/src/main/java/net/fabricmc/fabric/api/client/render/v1/HudRenderCallback.java
  fabric-rendering-v1/src/main/java/net/fabricmc/fabric/api/client/render/v1/InvalidateRenderStateCallback.java
  fabric-rendering-v1/src/main/java/net/fabricmc/fabric/impl/client/render/BlockEntityRendererRegistryImpl.java
  fabric-rendering-v1/src/main/java/net/fabricmc/fabric/impl/client/render/EntityRendererRegistryImpl.java
  fabric-rendering-v1/src/main/java/net/fabricmc/fabric/mixin/client/rendering/MixinBlockEntityRenderDispatcher.java
  fabric-rendering-v1/src/main/java/net/fabricmc/fabric/mixin/client/rendering/MixinEntityRenderManager.java
  fabric-rendering-v1/src/main/java/net/fabricmc/fabric/mixin/client/rendering/MixinInGameHud.java
  fabric-rendering-v1/src/main/java/net/fabricmc/fabric/mixin/client/rendering/MixinWorldRenderer.java
  fabric-rendering-v1/src/main/resources/assets/fabric-rendering-v1/icon.png
  fabric-rendering-v1/src/main/resources/fabric-rendering-v1.mixins.json
  fabric-rendering-v1/src/main/resources/fabric.mod.json
  settings.gradle
Labels: documentation, enhancement, last call

#18 Armor Api v1
  build.gradle
  fabric-armor-api-v1/build.gradle
  fabric-armor-api-v1/src/main/java/net/fabricmc/fabric/api/armor/v1/ArmorMaterial.java
  fabric-armor-api-v1/src/main/java/net/fabricmc/fabric/impl/armor/EquipmentSlot.java
  fabric-armor-api-v1/src/main/java/net/fabricmc/fabric/impl/armor/FabricArmorItem.java
  fabric-armor-api-v1/src/main/java/net/fabricmc/fabric/mixin/armor/MixinArmorItem.java
  fabric-armor-api-v1/src/main/java/net/fabricmc/fabric/mixin/armor/MixinClass1183.java
  fabric-armor-api-v1/src/main/resources/assets/fabric-armor-api-v1/icon.png
  fabric-armor-api-v1/src/main/resources/fabric-armor-api-v1.mixins.json
  fabric-armor-api-v1/src/main/resources/fabric.mod.json
  fabric-armor-api-v1/src/testmod/java/net/fabricmc/fabric/test/armor/ArmorTest.java
  fabric-armor-api-v1/src/testmod/resources/assets/fabric-armor-api-v1/models/items/potato_boots.json
  fabric-armor-api-v1/src/testmod/resources/assets/fabric-armor-api-v1/models/items/potato_chestplate.json
  fabric-armor-api-v1/src/testmod/resources/assets/fabric-armor-api-v1/models/items/potato_helmet.json
  fabric-armor-api-v1/src/testmod/resources/assets/fabric-armor-api-v1/models/items/potato_leggings.json
  fabric-armor-api-v1/src/testmod/resources/assets/fabric-armor-api-v1/textures/models/armor/potato_layer_1.png
  fabric-armor-api-v1/src/testmod/resources/assets/fabric-armor-api-v1/textures/models/armor/potato_layer_2.png
  fabric-armor-api-v1/src/testmod/resources/fabric.mod.json
  settings.gradle
Labels: enhancement

#19 Gamerules
  build.gradle
  fabric-gamerule-api-v1/build.gradle
  fabric-gamerule-api-v1/src/main/java/net/fabricmc/fabric/api/gamerule/v1/GameRulesInitializedCallback.java
  fabric-gamerule-api-v1/src/main/java/net/fabricmc/fabric/mixin/gamerule/MixinGameRules.java
  fabric-gamerule-api-v1/src/main/resources/assets/fabric-gamerule-api-v1/icon.png
  fabric-gamerule-api-v1/src/main/resources/fabric-gamerule-api-v1.mixins.json
  fabric-gamerule-api-v1/src/main/resources/fabric.mod.json
  settings.gradle
Labels: enhancement, possibly not required

#20 fix gamerule mixin name
  fabric-gamerule-api-v1/src/main/resources/fabric.mod.json
Labels: bug, critical, last call

#21 Curseforge integration
  build.gradle
Labels: enhancement

#23 Block place and Block break events
  build.gradle
  fabric-events-interaction-v0/build.gradle
  fabric-events-interaction-v0/src/main/java/net/fabricmc/fabric/api/event/player/BreakBlockCallback.java
  fabric-events-interaction-v0/src/main/java/net/fabricmc/fabric/api/event/player/PlaceBlockCallback.java
  fabric-events-interaction-v0/src/main/java/net/fabricmc/fabric/mixin/event/interaction/MixinItemStack.java
  fabric-events-interaction-v0/src/main/java/net/fabricmc/fabric/mixin/event/interaction/MixinServerPlayerInteractionManager.java
  fabric-events-interaction-v0/src/main/resources/fabric-events-interaction-v0.mixins.json
Labels: documentation, enhancement

#25 custom payload events
  build.gradle
  fabric-lifecycle-events-v1/build.gradle
  fabric-lifecycle-events-v1/src/main/java/net/fabricmc/fabric/api/client/event/lifecycle/v1/ClientNetworkEvents.java
  fabric-lifecycle-events-v1/src/main/java/net/fabricmc/fabric/api/event/lifecycle/v1/ServerNetworkEvents.java
  fabric-lifecycle-events-v1/src/main/java/net/fabricmc/fabric/mixin/event/lifecycle/MixinServerPlayNetworkHandler.java
  fabric-lifecycle-events-v1/src/main/java/net/fabricmc/fabric/mixin/event/lifecycle/client/MixinClientPlayNetworkHandler.java
  fabric-lifecycle-events-v1/src/main/resources/fabric-lifecycle-events-v1.mixins.json
  fabric-networking-v0/build.gradle
  fabric-networking-v0/src/main/java/net/fabricmc/fabric/mixin/network/MixinServerPlayNetworkHandler.java
Labels: documentation, enhancement

#26 Migrate a testmod and add item groups testmod
  fabric-api-base/src/main/resources/fabric.mod.json
  fabric-armor-api-v1/src/main/resources/fabric.mod.json
  fabric-commands-v0/src/main/resources/fabric.mod.json
  fabric-content-registries-v1/src/main/resources/fabric.mod.json
  fabric-crash-report-info-v1/src/main/resources/fabric.mod.json
  fabric-events-interaction-v0/src/main/resources/fabric.mod.json
  fabric-events-lifecycle-v0/src/main/resources/fabric.mod.json
  fabric-gamerule-api-v1/src/main/resources/fabric.mod.json
  fabric-item-groups-v0/src/main/resources/fabric.mod.json
  fabric-item-groups-v0/src/testmod/java/net/fabricmc/fabric/test/client/item/group/ItemGroupTest.java
  fabric-item-groups-v0/src/testmod/resources/fabric.mod.json
  fabric-key-binding-api-v1/build.gradle
  fabric-key-binding-api-v1/src/main/resources/fabric.mod.json
  fabric-key-binding-api-v1/src/testmod/java/net/fabricmc/fabric/test/client/keybinding/KeyBindingsTest.java
  fabric-lifecycle-events-v1/src/main/resources/fabric.mod.json
  fabric-networking-v0/src/main/resources/fabric.mod.json
  fabric-rendering-v1/src/main/resources/fabric.mod.json
  fabric-resource-loader-v0/src/main/resources/fabric.mod.json
  src/main/resources/fabric.mod.json
Labels: enhancement

#29 Climbable block api
  build.gradle
  fabric-content-registries-v1/build.gradle
  fabric-content-registries-v1/src/main/java/net/fabricmc/fabric/api/content/registry/v1/Climbable.java
  fabric-content-registries-v1/src/main/java/net/fabricmc/fabric/mixin/content/registries/MixinLivingEntity.java
  fabric-content-registries-v1/src/main/resources/fabric-content-registries-v1.mixins.json
Labels: enhancement, last call

#28 Recipe api v1
  build.gradle
  fabric-recipes-v1/build.gradle
  fabric-recipes-v1/src/main/java/net/fabricmc/fabric/api/recipe/v1/FabricRecipeRemainder.java
  fabric-recipes-v1/src/main/java/net/fabricmc/fabric/api/recipe/v1/RecipeEvents.java
  fabric-recipes-v1/src/main/java/net/fabricmc/fabric/mixin/recipe/MixinCraftingResultSlot.java
  fabric-recipes-v1/src/main/resources/assets/fabric-recipes-v1/icon.png
  fabric-recipes-v1/src/main/resources/fabric-recipes-v1.mixins.json
  fabric-recipes-v1/src/main/resources/fabric.mod.json
  settings.gradle
Labels: documentation, enhancement, last call, new module

#27 Material Builder
  build.gradle
  fabric-object-builder-api-v1/build.gradle
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/block/FabricBlockMaterial.java
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/mixin/object/builder/MaterialAccessor.java
  fabric-object-builder-api-v1/src/main/resources/assets/fabric-object-builder-api-v1/icon.png
  fabric-object-builder-api-v1/src/main/resources/fabric-object-builder-api-v1.mixins.json
  fabric-object-builder-api-v1/src/main/resources/fabric.mod.json
  fabric-object-builder-api-v1/src/testmod/java/net/fabricmc/fabric/test/object/builder/ObjectBuilderTest.java
  fabric-object-builder-api-v1/src/testmod/resources/assets/fabric-object-builder-api-v1-testmod/blockstates/test_block.json
  fabric-object-builder-api-v1/src/testmod/resources/fabric.mod.json
  settings.gradle
Labels: enhancement, last call, new module

#34 Two more content registry interfaces
  build.gradle
  fabric-api-base/build.gradle
  fabric-api-base/src/main/resources/fabric.mod.json
  fabric-armor-api-v1/build.gradle
  fabric-armor-api-v1/src/main/resources/fabric.mod.json
  fabric-commands-v0/build.gradle
  fabric-commands-v0/src/main/resources/fabric.mod.json
  fabric-content-registries-v1/build.gradle
  fabric-content-registries-v1/src/main/java/net/fabricmc/fabric/api/content/registry/v1/PlayerBlockHarvestListener.java
  fabric-content-registries-v1/src/main/java/net/fabricmc/fabric/api/content/registry/v1/UseTickable.java
  fabric-content-registries-v1/src/main/java/net/fabricmc/fabric/mixin/content/registries/MixinPlayerEntity.java
  fabric-content-registries-v1/src/main/java/net/fabricmc/fabric/mixin/content/registries/MixinServerPlayerInteractionManager.java
  fabric-content-registries-v1/src/main/resources/fabric-content-registries-v1.mixins.json
  fabric-content-registries-v1/src/main/resources/fabric.mod.json
  fabric-crash-report-info-v1/build.gradle
  fabric-crash-report-info-v1/src/main/resources/fabric.mod.json
  fabric-events-interaction-v0/build.gradle
  fabric-events-interaction-v0/src/main/resources/fabric.mod.json
  fabric-events-lifecycle-v0/build.gradle
  fabric-events-lifecycle-v0/src/main/resources/fabric.mod.json
  fabric-gamerule-api-v1/build.gradle
  fabric-gamerule-api-v1/src/main/resources/fabric.mod.json
  fabric-item-groups-v0/build.gradle
  fabric-item-groups-v0/src/main/resources/fabric.mod.json
  fabric-key-binding-api-v1/build.gradle
  fabric-key-binding-api-v1/src/main/resources/fabric.mod.json
  fabric-lifecycle-events-v1/build.gradle
  fabric-lifecycle-events-v1/src/main/resources/fabric.mod.json
  fabric-networking-v0/build.gradle
  fabric-networking-v0/src/main/resources/fabric.mod.json
  fabric-object-builder-api-v1/build.gradle
  fabric-object-builder-api-v1/src/main/resources/fabric.mod.json
  fabric-recipes-v1/build.gradle
  fabric-recipes-v1/src/main/resources/fabric.mod.json
  fabric-rendering-v1/build.gradle
  fabric-rendering-v1/src/main/resources/fabric.mod.json
  fabric-resource-loader-v0/build.gradle
  fabric-resource-loader-v0/src/main/resources/fabric.mod.json
  src/main/resources/fabric.mod.json
Labels: documentation, enhancement

#41 Better command API
  build.gradle
  fabric-commands-v1/build.gradle
  fabric-commands-v1/src/main/java/net/fabricmc/fabric/api/command/v1/CommandManager.java
  fabric-commands-v1/src/main/java/net/fabricmc/fabric/api/command/v1/DispatcherRegistrationCallback.java
  fabric-commands-v1/src/main/java/net/fabricmc/fabric/api/command/v1/ServerCommandSource.java
  fabric-commands-v1/src/main/java/net/fabricmc/fabric/impl/command/CommandManagerHolder.java
  fabric-commands-v1/src/main/java/net/fabricmc/fabric/mixin/command/MixinCommandManager.java
  fabric-commands-v1/src/main/java/net/fabricmc/fabric/mixin/command/MixinCommandRegistry.java
  fabric-commands-v1/src/main/resources/assets/fabric-commands-v1/icon.png
  fabric-commands-v1/src/main/resources/fabric-commands-v1.mixins.json
  fabric-commands-v1/src/main/resources/fabric.mod.json
  fabric-commands-v1/src/testmod/java/net/fabricmc/fabric/test/command/CommandTest.java
  fabric-commands-v1/src/testmod/resources/assets/fabric-commands-v1-testmod/icon.png
  fabric-commands-v1/src/testmod/resources/fabric.mod.json
  settings.gradle
Labels: enhancement, good first pull request
